from selenium import webdriver
from selenium.webdriver.common.by import By


class DoskaLocators:
    LOGIN_AND_REGISTRATION_BUTTON = (By.XPATH, "//button[@class='buttonSecondary inButtonText undefined inButtonText']")
    NO_ACCOUNT_BUTTON = (By.XPATH, "//button[@class='buttonSecondary inButtonText undefined inButtonText']")
    INPUT_LOGIN = (By.XPATH,".//input[@class='input_inputStandart__JweLZ spanGlobal']")
    INPUT_PASSWORD = (By.XPATH, ".//input[@class='input_inputStandart__JweLZ spanGlobal']")
    LOGIN_BUTTON = (By.XPATH, "//button[@class='buttonPrimary inButtonText undefined inButtonText']")
    ACCOUNT_NOT_EXIST_BUTTON = (By.XPATH, "//button[contains(text(), 'Нет аккаунта')]")
    EMAIL_FIELD = (By.XPATH, ".//input[@placeholder='Введите Email']")
    PASSWORD_FIELD = (By.XPATH, ".//input[@placeholder='Пароль']")
    PASSWORD_FIELD_REPEAT = (By.XPATH, ".//input[@placeholder='Повторите пароль']")
    CREATE_ACCOUNT = (By.XPATH, "//button[@class='buttonPrimary inButtonText undefined inButtonText' and text()='Создать аккаунт']")
    AVATAR = (By.XPATH, "//button[@class='circleSmall']")
    USER = (By.XPATH,"//h3[@class='profileText name']")
    MISTAKE = (By.XPATH,"//span[@class='input_span__yWPqB']")
    BOARDER_ERROR_EMAIL= (By.XPATH, "//div[@style='margin-bottom: 8px;' and @class='input_inputError__fLUP9']")
    BOARDER_ERROR_PASSWORD =(By.XPATH, "//div[@style='margin-bottom: 8px;' and @class='input_inputError__fLUP9']")
    BOARDER_ERROR_PASSWORD_REPEAT = (By.XPATH, "//div[@style='margin-bottom: 8px;' and @class='input_inputError__fLUP9']")
    ENTER = (By.XPATH, "//button[@class='buttonPrimary inButtonText undefined inButtonText' and text()='Войти']")
    EXIT = (By.XPATH, ".//button[contains(text(), 'Выйти')]")
    MODAL = (By.XPATH, "//form[@class='popUp_shell__LuyqR']")
    NAME_ADV = (By.XPATH, ".//input[@class='input_inputStandart__JweLZ spanGlobal' and @name='name']")
    TEXT_AREA = (By.XPATH, "//textarea[@class='textarea_inputStandart__IoNxq spanGlobal']")
    PRICE = (By.XPATH, ".//input[@class='input_inputStandart__JweLZ spanGlobal' and @name='price']")
    REKLAMA = (By.XPATH,"//button[@type='button' and text()='Разместить объявление']")
    DROPDOWN_ARROW = (By.XPATH, ".//button[@class='dropDownMenu_arrowDown__pfGL1 dropDownMenu_noDefault__wSKsP']")
    DROPDOWN = (By.XPATH, ".//div[@class='dropDownMenu_optionsMobile__LmXZM']")
    DROPDOWN_AUTO = (By.XPATH, ".//span[@class='undefined dropDownMenu_textColor__Nyo8k' and text()='Авто']]")
    PUBLISH = (By.XPATH, "// button[@type = 'submit' and text() = 'Опубликовать']")
    NEW_ADV = (By.XPATH, "//div[@class='grid_oneColumn__d5zrA']")
    MY_ADV = (By.XPATH, "//h1[@class='h1' and text()='Мои объявления']")